/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Luis Miguel
 */
public class DlgRegistro extends javax.swing.JDialog {

    /**
     * Creates new form DlgRegistro
     */
    public DlgRegistro(java.awt.Frame parent) {
        super(parent);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPanel = new javax.swing.JPanel();
        labelEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        labelPassword = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JPanel();
        labelGuardar = new javax.swing.JLabel();
        comboEleccion = new javax.swing.JComboBox<>();
        xPanel = new javax.swing.JPanel();
        xLabel = new javax.swing.JLabel();
        imagenFondo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        fondoPanel.setBackground(new java.awt.Color(255, 255, 255));
        fondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelEmail.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(204, 0, 204));
        labelEmail.setText("Email:");
        fondoPanel.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtEmail.setBorder(null);
        fondoPanel.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 200, 25));

        txtPassword.setBorder(null);
        fondoPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 200, 25));

        labelPassword.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(204, 0, 204));
        labelPassword.setText("Password:");
        fondoPanel.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(51, 204, 0));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelGuardar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        labelGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGuardar.setText("Guardar");

        javax.swing.GroupLayout btnGuardarLayout = new javax.swing.GroupLayout(btnGuardar);
        btnGuardar.setLayout(btnGuardarLayout);
        btnGuardarLayout.setHorizontalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );
        btnGuardarLayout.setVerticalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        fondoPanel.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, -1, -1));

        comboEleccion.setForeground(new java.awt.Color(204, 0, 204));
        comboEleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veterinario", "Administrador", " " }));
        comboEleccion.setBorder(null);
        fondoPanel.add(comboEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 99, 25));

        xPanel.setBackground(new java.awt.Color(255, 0, 0));
        xPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        xLabel.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        xLabel.setForeground(new java.awt.Color(255, 255, 255));
        xLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xLabel.setText("X");

        javax.swing.GroupLayout xPanelLayout = new javax.swing.GroupLayout(xPanel);
        xPanel.setLayout(xPanelLayout);
        xPanelLayout.setHorizontalGroup(
            xPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(xLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        xPanelLayout.setVerticalGroup(
            xPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(xLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        fondoPanel.add(xPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, -1));

        imagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vet-gc5daa2802_640.jpg"))); // NOI18N
        fondoPanel.add(imagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 370));
        fondoPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 102, 200, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JPanel getBtnGuardar() {
        return btnGuardar;
    }

    public void setBtnGuardar(JPanel btnGuardar) {
        this.btnGuardar = btnGuardar;
    }

    public JComboBox<String> getComboEleccion() {
        return comboEleccion;
    }

    public void setComboEleccion(JComboBox<String> comboEleccion) {
        this.comboEleccion = comboEleccion;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public void setTxtEmail(JTextField txtEmail) {
        this.txtEmail = txtEmail;
    }

    public JPasswordField getTxtPassword() {
        return txtPassword;
    }

    public JLabel getxLabel() {
        return xLabel;
    }

    public void setxLabel(JLabel xLabel) {
        this.xLabel = xLabel;
    }

    public JPanel getxPanel() {
        return xPanel;
    }

    public void setxPanel(JPanel xPanel) {
        this.xPanel = xPanel;
    }
      
    

    /**
     * @param args the command line arguments
     */
    public void setTxtPassword(JPasswordField txtPassword) {
        this.txtPassword = txtPassword;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JComboBox<String> comboEleccion;
    private javax.swing.JPanel fondoPanel;
    private javax.swing.JLabel imagenFondo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelGuardar;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JLabel xLabel;
    private javax.swing.JPanel xPanel;
    // End of variables declaration//GEN-END:variables
}
